### ISSUE TITLE
How can I save the form to databse?

### ISSUE THREAD

**Issue by mohammad1381** [meysampg/yii2-formbuilder#5]
How can I save the form to databse? and how can I use the form that I built for users?

**Comment by meysampg** [comment]
@mohammad1381 You can save `json` and regenerate form each time you need. Personally I implement a generator which read the `json` result of the form builder and generates `models`, `views` and `migrations` for it.

**Comment by paskuale75** [comment]
Small example in README.md ? Thanks

**Comment by paskuale75** [comment]
> @mohammad1381 You can save `json` and regenerate form each time you need. Personally I implement a generator which read the `json` result of the form builder and generates `models`, `views` and `migrations` for it.

Interesting this generator, can you give us a small example to understand more? tnx

**Comment by meysampg** [comment]
@paskuale75 Sorry. This extension is for long long ago. Currently I don't even develop in `php`.
