### ISSUE TITLE
Plugin is unable to handle the setting of a javascript function into the event handlers in the Options.

### ISSUE THREAD

**Issue by brianwong3** [meysampg/yii2-formbuilder#8]
Just wanted to let any users who decide to use this plugin that the current plugin does not allow the setting of a JsExpression into the Options for "onSave" or equivalent events.

Did some digging and found that the plugin _json_encode_s all the options and will throw a `Uncaught TypeError: d.config.opts.onSave is not a function` error.

`<?= FormBuilder::widget([
							'data' => Json::decode($form->survey_form) ,
							'dataType' => 'json',
							'options' => [ 
								'disableFields' => [ 'file','button','hidden','number', 'text', 'autocomplete', 'date' ],
								'disabledAttrs' => [ 'access' ],
								'disabledActionButtons' => ['data' ],
								'onSave' => new \yii\web\JsExpression('function(formData) { alert("asd"); }'),
							],
							'showActionButtons' => true
						]); ?>`

Slight fix is to remove the _json_encoding_ of the options instead use _\yii\helpers\Json::htmlEncode_ for the options as per what other plugins use.

In case anyone else does use this plugin.

**Comment by yii2backendwebdeveloper** [comment]
I am getting the same problem but i am unable to understand what solution you are offering. Could you please clear it again?

**Comment by i-internet** [comment]
Great thanks

**Comment by i-internet** [comment]
```
  private function getFBOptions()
    {
        $this->options = array_merge(
            [
                'dataType' => $this->dataType,
                'formData' => $this->{$this->arrayToTypeFunction}($this->data),
                'showActionButtons' => $this->showActionButtons,
            ],
            $this->options
        );

        if ($this->language) {
            $this->options['i18n'] = [
                'locale' => $this->language,
                'preloaded' => [
                    $this->language => $this->getMessages()
                ],
            ];
        }

        return \yii\helpers\Json::htmlEncode($this->options);
    }
```

This is what you need to do ``    return \yii\helpers\Json::htmlEncode($this->options); ``
